### PR TITLE
Let users select the color, which can extend beyond the base 16 colors

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by brymck — APPROVED** [review]

**Comment by brymck** [comment]
@anmull, thanks, look good. I've added configuration details to the readme with #2 as well.

**Comment by ghost** [comment]
Thanks. Just as a note to go along with the change, you can also add characters with the color changes.

printalias

**Comment by brymck** [comment]
Yeah, good idea! You can continue to use `PRINT_ALIAS_FORMAT` for this, but just to provide a cleaner separation of concerns I've added the ability to use `PRINT_ALIAS_PREFIX` (documented [here](https://github.com/brymck/print-alias#configuration)). In the future I might consider supporting global aliases—aliases that can appear anywhere in the line—so distinguishing between line prefix and formatting is probably good to have in place.

**Comment by ghost** [comment]
Great! Thanks for making that change, I'll update to using the prefix.

**Pull request merged**
